<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Version>3.0.0-Beta.15</Version>
    <PackageId>SAL3.Core</PackageId>
    <Authors>Kooklev P.A.</Authors>
    <Company>Pipindl</Company>
    <Product>SAL 3.0 Core</Product>
    <PackageTags>SAL3 Core</PackageTags>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <AssemblyVersion>3.0.0.15</AssemblyVersion>
    <FileVersion>3.0.0.15</FileVersion>
    <LangVersion>8</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="4.4.0" />
    <PackageReference Include="JsonDiffPatch.Net" Version="2.2.0" />
    <PackageReference Include="LiteDB" Version="4.1.4" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="3.1.9" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="3.1.9" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="3.1.9" />
    <PackageReference Include="NLog" Version="4.7.5" />
    <PackageReference Include="NLog.Extensions.Logging" Version="1.5.3" />
    <PackageReference Include="RabbitMQ.Client" Version="5.1.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SAL.API\SAL.API.csproj" />
    <ProjectReference Include="..\SAL.Infrastructure\SAL.Infrastructure.csproj" />
  </ItemGroup>
</Project>