<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Authors>Kooklev P.A.</Authors>
    <Company>
    </Company>
    <Product>SAL 3.0 Infrastructure</Product>
    <Version>3.0.0-Beta.15</Version>
    <PackageTags>SAL3 Infrastructure</PackageTags>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <PackageId>SAL3.Infrastructure</PackageId>
    <AssemblyVersion>3.0.0.15</AssemblyVersion>
    <FileVersion>3.0.0.15</FileVersion>
  </PropertyGroup>
</Project>