<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <Authors>Kooklev P.A.</Authors>
    <Company>
    </Company>
    <Product>SAL 3.0 Infrastructure</Product>
    <Version>3.1.0</Version>
    <PackageTags>SAL3 Infrastructure</PackageTags>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <PackageId>SAL3.Infrastructure</PackageId>
    <LangVersion>9</LangVersion>
  </PropertyGroup>
</Project>