<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <Authors>Kooklev P.A.</Authors>
    <Company>Pipindl</Company>
    <Product>SAL 3.0 API</Product>
    <Version>3.0.0-Beta.15</Version>
    <PackageTags>SAL3 API</PackageTags>
    <PackageId>SAL3.API</PackageId>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <LangVersion>9</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Autofac" Version="6.0.0" />
    <PackageReference Include="JsonDiffPatch.Net" Version="2.3.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="5.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="Newtonsoft.Json.Bson" Version="1.0.2" />
    <PackageReference Include="Newtonsoft.Json.Schema" Version="3.0.14" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SAL.Infrastructure\SAL.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="SystemCommand" />
  </ItemGroup>
</Project>